/** Ürün yazıları — 18 Eyl 2026. HeliaLoop, JuriLoop ve Eco-Report için 3'er yazı, TR ve EN (Hasan: yalnızca bu üçü).
 *  KURAL: yazılarda ürün hakkında yalnızca doğrulanmış özellik anlatılır
 *  (kaynak: TONSORA-OZELLIKLER.md, PALETRA/MAGAZA-METINLERI.md, Eco-Report SAHA-KITAPCIGI.md, site.ts ürün metinleri).
 *  Yasaklı ifadeler: "Türkiye'nin ilk", "otomatik hatırlatma", SMS, "resmî/AB onaylı rapor", mağazada olmayan uygulama için "indir". */
import type { LegacyArticle } from "./legacyArticles";

const TARIH = "2026-09-18";

type Taslak = Omit<LegacyArticle, "path" | "date">;

const tr = (a: Taslak): LegacyArticle => ({ ...a, path: `/blog/${a.slug}`, date: TARIH });
const en = (a: Taslak): LegacyArticle => ({ ...a, path: `/en/blog/${a.slug}`, date: TARIH });

export const urunYazilariTr: LegacyArticle[] = [
  // ─── ECO-REPORT ───
  tr({
    slug: "blog-ai-act-yuksek-risk-ertelendi-ama-2-aralik-2026-iki-yeni-yasak-geliyor",
    product: "eco-report",
    category: "AI Act",
    title: "AI Act: Yüksek Risk Ertelendi — Ama 2 Aralık 2026'da İki Yeni Yasak Yürürlüğe Giriyor",
    excerpt: "Dijital Omnibus yüksek risk takvimini 2 Aralık 2027'e erteledi. Buna karşılık madde 5'e eklenen iki yeni yasak 2 Aralık 2026'da başlıyor.",
    body: [
      "Yapay Zekâ Tüzüğü (AB) 2024/1689'un genel uygulama tarihi **2 Ağustos 2026**. Ancak tüzüğün takvimi tek bir tarihten ibaret değil ve **2026/1744 sayılı Dijital Omnibus Tüzüğü ile değişti.**",
      "Takvim bugün nasıl görünüyor?",
      "Yasaklanmış uygulamalar ve yapay zekâ okuryazarlığını içeren Bölüm I ve II **2 Şubat 2025** tarihinden beri uygulanıyor. Genel amaçlı yapay zekâ ve yönetişim hükümleri **2 Ağustos 2025**'de başladı.",
      "Dijital Omnibus ile **yüksek risk yükümlülükleri ertelendi**: Ek III kapsamındaki yüksek riskli sistemler için **2 Aralık 2027**, Ek I kapsamındaki ürün güvenliği hattı için **2 Ağustos 2028**.",
      "Erteleme rahatlama değil",
      "Aynı değişiklik madde 5'e **iki yeni yasak** ekledi — (ba) ve (bb) bentleri — ve bunlar **2 Aralık 2026** tarihinden itibaren geçerli. Yasaklar tüzüğün en sert ucudur: yüksek risk gibi \"belgelendirip piyasaya sürme\" meselesi değil, **yapılmaması gereken** uygulamalardır.",
      "Madde 5'teki yasaklı uygulama sayısı bu eklemelerle birlikte **10**'a çıkıyor. Ayrıca aynı tarihte madde 50(2) kapsamındaki işaretleme yükümlülüğü için bir geçiş süresi başlıyor.",
      "Sıra önemli: önce yasak, sonra sınıf",
      "Pratikte doğru sıra şudur: (1) sistem **yasaklı uygulamalardan birine** giriyor mu? (2) girmiyorsa **yüksek riskli** mi? Ek III sekiz alan sayar (biyometri, kritik altyapı, eğitim, istihdam, temel hizmetlere erişim, kolluk, göç/sınır, adalet ve demokratik süreçler) — toplam **8** alan. (3) yüksek risk değilse şeffaflık yükümlülüğü var mı?",
      "Bu sıra atlanırsa en pahalı hata yapılır: yasaklı bir uygulamayı \"yüksek risk\" sanıp belgelendirmeye çalışmak. Yasaklı uygulama belgelendirilerek meşrulaştırılamaz.",
      "Yüksek risk belgelendirme yükü",
      "Yüksek riskli sistem için Ek IV, teknik dosyada bulunması gereken **9 unsur** sayar: sistemin genel tanımı, geliştirme süreci, izleme ve kontrol, risk yönetimi ve diğerleri. Erteleme bu yükü kaldırmaz, yalnızca başlangıç tarihini öteler.",
      "Nechh Eco-Report'ta durum",
      "Eco-Report'un AI Act modülü yasaklı uygulama, yüksek risk ve şeffaflık sınıflandırmasını bu sırayla sorar ve Ek IV teknik dosya listesini çıkarır. Değişiklik zinciri (2026/1744) makineyle izlenir; bir soru cevaplanmadığında modül tahmin etmez, \"karar verilemedi\" der. Eco-Report hazırlık aracıdır; uygunluk değerlendirmesi yerine geçmez.",
      "Kaynak: Tüzük (AB) 2024/1689 (Yapay Zekâ Tüzüğü) ve değişiklik Tüzük (AB) 2026/1744 (Dijital Omnibus), EUR-Lex.",
      "Yayın notu: Bu içerik genel bilgilendirme amaçlıdır; hukuki görüş, uygunluk değerlendirmesi veya şirkete özel uyum değerlendirmesi değildir. Nihai karar resmî metne ve gerektiğinde hukuki danışmanlığa dayanır.",
    ],
  }),
  tr({
    slug: "blog-dijital-urun-pasaportu-zorunlu-mu-henuz-hicbir-urun-icin-degil",
    product: "eco-report",
    category: "DPP",
    title: "Dijital Ürün Pasaportu Zorunlu mu? Henüz Hiçbir Ürün İçin Değil — Peki Ne Zaman?",
    excerpt: "ESPR hiçbir ürün için dijital ürün pasaportunu doğrudan zorunlu kılmaz; zorunluluk ürün grubu bazında çıkarılan delege tüzüklerle gelir. Bu ayrım satın alma kararını değiştirir.",
    body: [
      "Dijital Ürün Pasaportu (DPP) hakkında en çok yapılan hata, onu bugün yürürlükte olan genel bir zorunluluk sanmaktır.",
      "Doğrusu şu: **Sürdürülebilir Ürünler İçin Eko-Tasarım Tüzüğü (ESPR, (AB) 2024/1781) hiçbir ürün için dijital ürün pasaportunu doğrudan zorunlu kılmaz.** Zorunluluk, madde 4 uyarınca **ürün grubu bazında çıkarılan delege tüzüklerle** gelir (madde 9(1)-(2)).",
      "Bu neden önemli?",
      "Çünkü \"DPP zorunlu oldu, hemen sistem alın\" diyen bir satıcıya verilecek cevap, ürün grubunuz için bir delege tüzük **çıkmış mı** sorusudur. Çıkmadıysa sizin için bir tarih de yoktur. Eco-Report'un DPP modülü tam bu yüzden delege tüzük durumunu sorar ve durum bilinmeden **zorunluluk iddia etmez**.",
      "Hazırlık yine de anlamlı",
      "ESPR'nin III. Bölümü dijital ürün pasaportunu **7 madde** üzerinden tanımlar ve Ek III, pasaportta bulunabilecek **12 veri unsurunu** sayar. Delege tüzük çıktığında istenecek veri bu çerçevenin içinden gelir; bu yüzden veri toplama altyapısını önceden kurmak boşa emek değildir.",
      "Pratikte asıl zorluk pasaportun kendisi değil, **veriyi tedarik zincirinden toplamaktır**. Malzeme bileşimi, onarılabilirlik, geri dönüşüm oranı gibi bilgiler çoğu zaman üreticinin kendi kayıtlarında yoktur; tedarikçiden istenmesi gerekir. Bu talep bir delege tüzük çıktıktan sonra başlatılırsa geç kalınır.",
      "ESPR ayrıca bir dijital ürün pasaportu kayıt sistemi öngörür; tüzükte bu sistem için **19 Temmuz 2026** tarihi geçer.",
      "Ne yapmalı?",
      "1) Ürün grubunuz için çalışma programında bir delege tüzük var mı, takip edin. 2) Ek III'teki veri unsurlarını kendi ürününüz için kim sağlayacak, şimdiden eşleştirin. 3) \"DPP zorunlu\" diyen her iddiayı **hangi delege tüzük** sorusuyla sınayın.",
      "Nechh Eco-Report'ta durum",
      "Eco-Report'un DPP modülü, delege tüzük durumu bilinmeden yükümlülük üretmez; varsayılan seçenek \"bilinmiyor\"dur ve bu durumda modül \"karar verilemedi\" der. Ek III veri unsurları hazırlık listesi olarak çıkarılır. Eco-Report hazırlık aracıdır; resmî beyan veya uygunluk değerlendirmesi yerine geçmez.",
      "Kaynak: Tüzük (AB) 2024/1781 (ESPR), EUR-Lex.",
      "Yayın notu: Bu içerik genel bilgilendirme amaçlıdır; hukuki görüş, uygunluk değerlendirmesi veya şirkete özel uyum değerlendirmesi değildir. Nihai karar resmî metne ve gerektiğinde hukuki danışmanlığa dayanır.",
    ],
  }),
  tr({
    slug: "blog-csrd-esikleri-degisti-450-milyon-euro-ve-1000-calisan",
    product: "eco-report",
    category: "CSRD",
    title: "CSRD Eşikleri Değişti: 450 milyon € VE 1.000 Çalışan — Eşiğin Altındaysanız Ne Oluyor?",
    excerpt: "Omnibus I, CSRD kapsamını daralttı: artık yalnızca hem ciro hem çalışan eşiğini aşan teşebbüsler raporluyor. Borsaya kote KOBİ yükümlülüğü silindi.",
    body: [
      "Sürdürülebilirlik raporlaması hakkında dolaşan eşiklerin çoğu **eski**. Omnibus I olarak bilinen (AB) 2026/470 sayılı Direktif, CSRD kapsamını önemli ölçüde daralttı.",
      "Güncel kural",
      "Bilanço tarihinde **hem 450 milyon € net ciroyu hem de ortalama 1.000 çalışanı** aşan teşebbüsler, yönetim raporlarında sürdürülebilirlik bilgisi vermekle yükümlü. Dikkat: iki eşik **VE** ile bağlı. Yalnızca birini aşmak yükümlülük doğurmaz.",
      "Ayrıca **borsaya kote KOBİ'ler için öngörülen yükümlülük (eski madde 5(2)(c)) silindi.**",
      "İlk raporlama, **1 January 2027** tarihinde veya sonrasında başlayan mali yıllar için geçerli.",
      "Eşiğin altındaysanız: raporlamıyorsunuz — ama sorular geliyor",
      "Asıl mesele burada. Eşiğin altındaki bir firma **raporlamak zorunda değildir**; ancak kapsamdaki bir müşterinin değer zincirindeyse o müşteriden veri talebi gelir. Çoğu Türk tedarikçisi CSRD ile ilk kez böyle karşılaşıyor.",
      "Direktif bu noktada bir koruma getiriyor: sürdürülebilirlik raporlama standartları, değer zincirindeki aktörlerden -özellikle raporlama yükümlülüğü **olmayanlardan**- bilgi toplamanın zorluğunu dikkate almak zorunda. **1.000 çalışanı aşmayan** teşebbüslerden istenebilecek bilgi için bir üst sınır öngörülüyor.",
      "Pratik sonuç: kapsamdaki müşteriniz sizden sınırsız veri isteyemez. Gelen talebin bu sınırla uyumlu olup olmadığı sorulabilir bir sorudur.",
      "ESRS standartları",
      "Raporlamanın içeriğini Avrupa Sürdürülebilirlik Raporlama Standartları (ESRS) belirler; yürürlükteki delege tüzük **12 standart** sayar (ESRS 1 ve 2 genel, kalanlar çevre, sosyal ve yönetişim başlıkları).",
      "Neden eski eşiklerle çalışmak tehlikeli?",
      "Çünkü eski eşiklerle yapılan bir değerlendirme, yükümlü olmayan bir firmaya yükümlülük satar. Bu sadece gereksiz maliyet değil, yanlış beyan riskidir. Eşik, ciro ve çalışan sayısı gibi görünen ama **hangi metin sürümünden okunduğuna** bağlı bir veridir.",
      "Nechh Eco-Report'ta durum",
      "Eco-Report'un CSRD modülü eşikleri Omnibus I metninden okur; değer zinciri korumasını ve kapsam dışı olma hâlini ayrı ayrı değerlendirir. Mevzuat değişikliği makineyle izlenir. Eco-Report hazırlık aracıdır; denetim veya resmî beyan yerine geçmez.",
      "Kaynak: Direktif (AB) 2022/2464 (CSRD), Direktif (AB) 2026/470 (Omnibus I) ve Delege Tüzük (AB) 2023/2772 (ESRS), EUR-Lex.",
      "Yayın notu: Bu içerik genel bilgilendirme amaçlıdır; hukuki görüş, uygunluk değerlendirmesi veya şirkete özel uyum değerlendirmesi değildir. Nihai karar resmî metne ve gerektiğinde hukuki danışmanlığa dayanır.",
    ],
  }),
  tr({
    slug: "blog-cra-nedir-ab-ye-yazilim-satan-uretici-kapsamda-mi",
    product: "eco-report",
    category: "CRA",
    title: "Siber Dayanıklılık Tüzüğü (CRA) Nedir? AB'ye Yazılım Satan Üretici Kapsamda mı?",
    excerpt: "CRA, AB pazarına sunulan dijital öğeli ürünlere uygulanır ve üreticinin AB'de kurulu olmasını şart koşmaz. Bildirim yükümlülüğü 11 Eylül 2026 tarihinden beri yürürlükte.",
    body: [
      "Siber Dayanıklılık Tüzüğü (Cyber Resilience Act, CRA), AB pazarına sunulan **dijital öğeli ürünler** için siber güvenlik gereklilikleri koyar. \"Dijital öğeli ürün\" ifadesi yalnızca donanımı değil, **yazılımı da** kapsar.",
      "Kimi kapsar?",
      "Tüzük, üreticinin AB'de kurulu olmasını şart koşmaz. Ürün AB pazarına giriyorsa yükümlülük üretici, ithalatçı ve distribütör arasında paylaşılır. Bunun pratik anlamı şudur: **Türkiye'de yerleşik bir yazılım üreticisi, ürününü AB'ye satıyorsa doğrudan kapsamdadır.**",
      "Bu, DORA'dan farklıdır. DORA'da yükümlülük AB'deki finans kuruluşundadır ve tedarikçiye **sözleşmeyle** yansır. CRA'da yük doğrudan tüzükten doğar.",
      "Takvim — bir yükümlülük zaten yürürlükte",
      "Tüzüğün genel uygulama tarihi **11 Aralık 2027**. Ancak iki istisna var: onaylanmış kuruluşlara ilişkin Bölüm IV **11 Haziran 2026**, **madde 14 bildirim yükümlülüğü ise 11 Eylül 2026** tarihinden beri uygulanmaktadır.",
      "Yani aktif olarak sömürülen zafiyet ve ciddi güvenlik olayı bildirimi için saatler **bugün** işliyor: erken uyarı 24 saat, bildirim 72 saat, nihai rapor 14 gün.",
      "Önce kapsam dışı mısınız?",
      "Tüzük; tıbbi cihaz, in vitro tanı cihazı ve motorlu araç mevzuatına tabi ürünlere, sivil havacılıkta sertifikalandırılmış ürünlere, denizcilik ekipmanına, aynı teknik özelliklerle üretilen yedek parçalara ve yalnızca ulusal güvenlik/savunma amacıyla geliştirilen ürünlere uygulanmaz. Bunlardan birine giriyorsanız CRA sizin için geçerli değildir.",
      "Ayrıca Tüzük (AB) 2025/327 (Avrupa Sağlık Veri Alanı) CRA'yı değiştirdi: o tüzük kapsamında **EHR sistemi** sayılan ürünler, uygunluğu 2025/327'deki usulle gösterir. Bu değerlendirme ürün sınıfından **önce** gelir.",
      "Ürün sınıfı değerlendirme yolunu belirler",
      "Ek III, önemli ürünleri iki sınıfa ayırır (sınıf I'de 19, sınıf II'de 4 kalem) ve ayrıca 3 kalemlik kritik ürün listesi vardır. Listelerin hiçbirinde değilseniz ürün \"diğer\" sayılır; **Ek I gereklilikleri yine geçerlidir**, yalnızca uygunluk değerlendirme yolu daha esnektir.",
      "Dikkat edilmesi gereken nokta: sınıf I önemli ürünlerde uyumlaştırılmış standartları uygulamadıysanız veya kısmen uyguladıysanız, iç kontrol yolu kapanır ve üçüncü taraf içeren yollardan birine geçmeniz gerekir.",
      "Üç ayrı iş paketi",
      "CRA üç farklı işi aynı anda ister: Ek I Bölüm I'deki **13 ürün gerekliliği**, Ek I Bölüm II'deki **8 zafiyet yönetimi gerekliliği** ve Ek VII'deki **8 unsurlu teknik dosya**. Bunlar birbirinin yerine geçmez: ürün güvenli olsa bile zafiyet yönetimi süreci yoksa uygunluk yoktur.",
      "Destek süresi",
      "Üretici, ürün için bir destek süresi belirlemek ve bunu kullanıcıya açıkça duyurmak zorundadır. Tüzüğün alt sınırı **en az 5 yıl**; yayımlanan bir güvenlik güncellemesinin erişilebilir kalma süresi ise **en az 10 yıl**. Süre, ürünün beklenen kullanım ömrüne göre belirlenir: kısa ömürlü ürün için alt sınırın altına inilemez, uzun ömürlü üründe alt sınır yeterli olmayabilir.",
      "Nechh Eco-Report'ta durum",
      "Eco-Report'un CRA modülü ürün sınıfını, uygunluk yolunu ve destek süresini resmî metinden okunan verilerle değerlendirir; bir soru cevaplanmadığında tahmin etmez, \"karar verilemedi\" der. Ayrıca CRA Üretici Hazırlık Kiti, Ek I, Ek III ve Ek VII'yi çalışılabilir dosyalara çevirir. Eco-Report bir hazırlık aracıdır; uygunluk değerlendirmesi veya CE işareti yerine geçmez.",
      "Kaynak: Tüzük (AB) 2024/2847 (Siber Dayanıklılık Tüzüğü), EUR-Lex; değişiklik: Tüzük (AB) 2025/327.",
      "Yayın notu: Bu içerik genel bilgilendirme amaçlıdır; hukuki görüş, uygunluk değerlendirmesi veya şirkete özel uyum değerlendirmesi değildir. Nihai karar resmî metne ve gerektiğinde hukuki danışmanlığa dayanır.",
    ],
  }),
  tr({
    slug: "blog-cra-madde-14-bildirim-24-72-saat-zaten-yururlukte",
    product: "eco-report",
    category: "CRA",
    title: "CRA Madde 14: 24/72 Saatlik Bildirim Yükümlülüğü 11 Eylül 2026'ten Beri Yürürlükte",
    excerpt: "CRA'nın geneli 11 Aralık 2027'de başlıyor; ancak bildirim yükümlülüğü 11 Eylül 2026 tarihinden beri uygulanıyor. Saat sıfırı ne zaman başlar?",
    body: [
      "Siber Dayanıklılık Tüzüğü'nün (AB) 2024/2847 geneli **11 Aralık 2027** tarihinde uygulanmaya başlayacak. Ancak tüzüğün kendi metni bir istisna koyuyor: **madde 14, 11 Eylül 2026 tarihinden itibaren** uygulanır.",
      "Bu, AB pazarına dijital öğeli ürün sunan üreticiler için şu anlama gelir: Ek I gereklilikleri ve teknik dosya için hâlâ zaman varken, **bildirim yükümlülüğü bugün geçerlidir.**",
      "Süreler",
      "Aktif olarak sömürülen bir zafiyet için: farkına varıldıktan itibaren **24 saat** içinde erken uyarı, **72 saat** içinde bildirim, **14 gün** içinde nihai rapor. Ciddi bir güvenlik olayı için nihai rapor süresi ise tüzükte \"bir ay\" olarak geçer.",
      "Bildirim, koordinatör olarak belirlenen CSIRT'e ve ENISA'ya yapılır.",
      "Saat sıfırı ne zaman başlar?",
      "Süre, üreticinin durumun **farkına varmasıyla** başlar. Bu yüzden asıl soru teknik değil, örgütseldir: \"farkına varma\" anı kim tarafından, nerede kayda geçiyor? Zafiyet bildirimleri hangi adrese düşüyor ve o adresi hafta sonu kim okuyor?",
      "Prosedürü olmayan bir ekip, olay anında önce bu soruları tartışır. Saatler o sırada işlemeye devam eder.",
      "Önceden yazılması gerekenler",
      "Bildirim kararını kim verir, raporu kim yazar, teknik incelemeyi kim yapar ve bu kişilerin **yedekleri** kimdir. Tek kişiye bağlı bir prosedür tatilde ve mesai dışında çalışmaz; saatler ise tatil beklemez.",
      "Zafiyetin alındığı iletişim noktası (koordineli zafiyet açıklama adresi) ve farkına varma zaman damgasının tutulduğu sistem de önceden belirlenmelidir.",
      "Bildirim tek başına yetmez",
      "Ek I Bölüm II, giderilen zafiyetin kamuya açıklanmasını, güvenlik güncellemesinin -teknik olarak mümkünse- işlev güncellemesinden **ayrı** dağıtılmasını ve en az üst düzey bağımlılıkları kapsayan, makineyle okunabilir bir yazılım malzeme listesinin (SBOM) tutulmasını ister. Bu bölümde toplam 8 süreç gerekliliği vardır.",
      "Nechh Eco-Report'ta durum",
      "CRA Üretici Hazırlık Kiti, madde 14 için bir bildirim prosedürü şablonu içerir: süreler tüzük metninden alınır, saat sıfırı, roller, yedekler ve olay kaydı alanları doldurulmak üzere bırakılır. Tüzükte yazmayan hiçbir süre şablona konmamıştır.",
      "Kaynak: Tüzük (AB) 2024/2847 (Siber Dayanıklılık Tüzüğü), EUR-Lex; değişiklik: Tüzük (AB) 2025/327.",
      "Yayın notu: Bu içerik genel bilgilendirme amaçlıdır; hukuki görüş, uygunluk değerlendirmesi veya şirkete özel uyum değerlendirmesi değildir. Nihai karar resmî metne ve gerektiğinde hukuki danışmanlığa dayanır.",
    ],
  }),
  tr({
    slug: "blog-cbam-varsayilan-degerler-2026-1740-duzeltmesi",
    product: "eco-report",
    category: "CBAM",
    title: "CBAM Varsayılan Değerleri Düzeltildi: 2026/1740 Ne Değiştirdi?",
    excerpt: "Komisyon, varsayılan değer tablolarını ayrı bir düzeltme tüzüğüyle güncelledi ve 1 Ocak 2026'ya geriye dönük uyguladı. Hangi satırlar etkilendi?",
    body: [
      "AB Komisyonu, CBAM varsayılan değerlerini belirleyen 2025/2621 sayılı Uygulama Tüzüğü'nün eklerini 2026/1740 sayılı Uygulama Tüzüğü ile düzeltti. Metin 31 Temmuz 2026'da AB Resmî Gazetesi'nde yayımlandı ve 1 Ocak 2026'dan itibaren geçerli olacak şekilde uygulanıyor.",
      "Neden dikkat edilmeli?",
      "Düzeltme ayrı bir tüzükle geldiği için 2025/2621'in kendi sayfasına bakan biri değişikliği göremeyebilir. Varsayılan değer kullanan her hesap, hangi tablo sürümüne dayandığını kontrol etmelidir.",
      "Ne değişti?",
      "Ek I ve Ek IV'teki bazı satırlar düzeltildi. Değişiklik bazı ülke-ürün satırlarında küçük, bazılarında büyüktür; örneğin Tunus satırlarında ve Ek IV'teki 7616 99 alt başlığında belirgin farklar var. Türkiye için 7208 51 20 (sıcak haddelenmiş yassı çelik) satırında toplam değer değişmedi.",
      "Nechh Eco-Report'ta durum",
      "Eco-Report'taki varsayılan değer tabloları 14 Eylül 2026'da 2026/1740 düzeltmesiyle güncellendi. Uygulamada her varsayılan değerin yanında dayandığı tüzük gösterilir. Eco-Report bir hazırlık aracıdır; resmî doğrulama yalnızca akredite doğrulayıcı tarafından yapılır.",
      "Kaynak: Commission Implementing Regulation (EU) 2026/1740 (correcting act) ve (EU) 2025/2621, EUR-Lex.",
    ],
  }),
  tr({
    slug: "blog-cbam-veri-vermeyen-ihracatci-ne-oder-cezali-ek",
    product: "eco-report",
    category: "CBAM",
    title: "Veri Vermeyen İhracatçı Ne Öder? CBAM Varsayılan Değerine Eklenen Pay",
    excerpt: "AB'deki alıcınız gerçek emisyon verisi alamazsa varsayılan değeri, üstüne eklenen payla birlikte kullanır. Fark 2026'dan 2028'e üç katına çıkar.",
    body: [
      "CBAM'de beyanı AB'deki ithalatçı verir; Türk ihracatçı beyan vermez, veri verir. İthalatçı üreticiden gerçek emisyon verisi alamazsa AB'nin yayımladığı varsayılan değeri kullanmak zorundadır.",
      "Varsayılan değerin üstüne eklenen pay",
      "2025/2621 sayılı Uygulama Tüzüğü'ne göre çelik, alüminyum, çimento ve hidrojende varsayılan değere 2026 için %10, 2027 için %20, 2028 ve sonrası için %30 ek uygulanır. Gübrede bu oran %1'dir.",
      "Rakamla bir örnek",
      "CN 7208 51 20, menşe Türkiye, 1.000 ton için varsayılan değer ile gerçek veri arasındaki farkın maliyeti, sertifika fiyatı €75,28 alındığında yaklaşık 2026'da €18.278, 2027'de €36.556, 2028'de €54.834'tür. Bu bir örnektir; sizin ürününüzün rakamı kendi verinizle hesaplanır. Sertifika fiyatı AB ETS'ye bağlı olduğundan değişir.",
      "Fark kime yansır?",
      "Maliyeti ithalatçı öder ama genellikle fiyat pazarlığında ihracatçıya geri döner ya da alıcı tedarikçi değiştirir.",
      "Nechh Eco-Report'ta nasıl işliyor?",
      "Eco-Report'ta menşe ülke, CN kodu, yıl ve tonaj girildiğinde resmî varsayılan değer ve ek dahil hali yan yana gösterilir. Gerçek veriyle hesap AB yöntemine göre yapılır ve her rakamın yanında kaynağı yazar.",
    ],
  }),
  tr({
    slug: "blog-cbam-50-ton-muafiyeti-kimin-tonaji-sayilir",
    product: "eco-report",
    category: "CBAM",
    title: "CBAM'de 50 Ton Muafiyeti: Kimin Tonajı Sayılır?",
    excerpt: "\"Yılda 50 tondan az satıyoruz, bizi ilgilendirmez\" cümlesi çoğu zaman yanlış. Sınır sizin satışınıza değil, AB'deki ithalatçının toplamına bakar.",
    body: [
      "2025/2083 sayılı Tüzük ile CBAM'e bir kütle eşiği eklendi: AB'deki bir ithalatçının kapsamdaki mallardan yıllık toplam net kütlesi 50 ton veya altındaysa CBAM yükümlülüğü doğmaz.",
      "Sınır kimin tonajına bakar?",
      "Eşik, ihracatçının tek satışına değil, ithalatçının bir yıl içinde tüm tedarikçilerinden yaptığı toplam alıma bakar. Size 20 ton sipariş veren alıcı başka yerlerden 200 ton alıyorsa eşiği çoktan aşmıştır.",
      "İstisnalar",
      "Elektrik ve hidrojen bu muafiyete girmez. Muafiyet kendiliğinden de işlemez; ithalatçı bunu gümrük beyanında belirtir.",
      "Ne yapmalı?",
      "Alıcınıza toplam CBAM tonajını ve sizden veri isteyip istemeyeceğini sorun. Veri isteniyorsa ilk yıllık beyan 2026 ithalatları için 30 Eylül 2027'ye kadar verilir; hazırlığı son aya bırakmamak gerekir.",
      "Nechh Eco-Report'ta nasıl işliyor?",
      "Eco-Report'ta tonaj girildiğinde muafiyet kontrolü anında yapılır. Muafsanız bunu açıkça söyler; muaf değilseniz gerçek veriyle hesap adımlarına geçilir.",
    ],
  }),

  // ─── HELIALOOP ───
  tr({
    slug: "blog-hasta-sevkinde-whatsapp-neden-yetmiyor",
    product: "helialoop",
    category: "HELIALOOP",
    title: "Hasta Sevkinde WhatsApp Neden Yetmiyor?",
    excerpt: "Meslektaşa hasta yönlendirmek çoğu zaman bir mesajla başlar ve orada kaybolur. Yönlendirmenin kayıp noktaları ve düzenli bir akışın faydası.",
    body: [
      "Bir hekim hastasını başka bir branşa yönlendirirken çoğu zaman bildiği bir meslektaşa mesaj atar. Mesaj okunur, hasta aranır ya da aranmaz; ilk hekim sonucu çoğu zaman öğrenemez.",
      "Kayıp noktaları",
      "Yönlendirme kaydı kişisel sohbetlerin arasında kaybolur. Hastanın randevu alıp almadığı bilinmez. Kim, hangi hastayı, hangi gerekçeyle yönlendirdi sorusunun cevabı toplu olarak görülemez. Hasta verisi de kişisel mesajlaşma uygulamalarında dağınık kalır.",
      "Düzenli bir akış neyi değiştirir?",
      "Yönlendirme ayrı bir kayıt olarak tutulduğunda hem gönderen hem alan hekim sürecin hangi adımda olduğunu görür. Sonraki adımın ve sorumluluğun netleşmesi, hastanın arada kaybolma ihtimalini düşürür.",
      "HeliaLoop'ta nasıl işliyor?",
      "HeliaLoop, hekimler ve klinisyenler arasındaki yönlendirme ve randevu koordinasyonunu tek bir çalışma alanında toplamak için tasarlandı: meslektaş arama, yönlendirme oluşturma ve takip, mesajlaşma ve müsaitlik ekranları bu akışın parçasıdır. HeliaLoop Google Play'de yayındadır.",
    ],
  }),
  tr({
    slug: "blog-sevk-notunda-olmasi-gerekenler",
    product: "helialoop",
    category: "HELIALOOP",
    title: "İyi Bir Sevk Notunda Neler Olmalı?",
    excerpt: "Eksik sevk notu hastayı ikinci kez aynı tetkiklere sokar. Meslektaşın ilk bakışta ihtiyaç duyduğu bilgiler.",
    body: [
      "Yönlendirilen hekimin ilk dakikası çoğu zaman \"bu hasta neden bana geldi?\" sorusuyla geçer. Kısa ama eksiksiz bir sevk notu hem zamanı hem hastanın tekrar tetkik yükünü azaltır.",
      "Temel başlıklar",
      "Yönlendirme gerekçesi ve beklenen soru; ilgili öykü ve mevcut tanılar; kullanılan ilaçlar ve alerjiler; yapılmış tetkiklerin sonuçları ve tarihleri; aciliyet derecesi; gönderen hekimin iletişim bilgisi.",
      "Geri bildirim döngüsü",
      "Sevk, hasta karşı tarafa ulaşınca bitmez. Alan hekimin değerlendirmesini gönderene iletmesi, hastanın bakımında sürekliliği sağlar ve meslektaşlar arası güveni artırır.",
      "Veri paylaşımında ölçü",
      "Sağlık verisi özel nitelikli kişisel veridir. Yalnızca yönlendirme için gerekli olan bilgi paylaşılmalı, kişisel mesajlaşma uygulamalarında dağınık bırakılmamalıdır.",
      "HeliaLoop'ta nasıl işliyor?",
      "HeliaLoop'ta yönlendirme ayrı bir kayıt olarak oluşturulur ve takip edilir; iki hekim de sürecin hangi adımda olduğunu görür. Bu yazı genel bilgi amaçlıdır, klinik veya hukuki tavsiye değildir.",
    ],
  }),
  tr({
    slug: "blog-hekimler-arasi-is-birliginde-hasta-verisi",
    product: "helialoop",
    category: "HELIALOOP",
    title: "Hekimler Arası İş Birliğinde Hasta Verisini Korumak",
    excerpt: "Sağlık verisi özel nitelikli kişisel veridir. Meslektaşla paylaşırken hangi ilkeler akılda tutulmalı?",
    body: [
      "6698 sayılı KVKK, sağlık verisini özel nitelikli kişisel veri olarak sayar ve işlenmesini sıkı şartlara bağlar. Meslektaşlar arası yönlendirme de bir veri paylaşımıdır.",
      "Üç temel ilke",
      "Gereklilik: yalnızca yönlendirme için gereken bilgi paylaşılmalıdır. Hukuki dayanak: paylaşım, hastanın onamına ya da kanundaki bir istisnaya dayanmalıdır. Güvenlik: veri kişisel telefon galerilerinde ve genel mesajlaşma gruplarında dağınık kalmamalıdır.",
      "Kişisel mesajlaşmanın riski",
      "Genel amaçlı mesajlaşma uygulamasında gönderilen tahlil fotoğrafı telefon yedeğine, galeriye ve bazen başka sohbetlere taşınır. Kimin hangi veriye eriştiği sonradan izlenemez.",
      "HeliaLoop'ta nasıl işliyor?",
      "HeliaLoop, yönlendirme ve mesajlaşmayı hekimlere özel bir çalışma alanında toplar; hasta onamı için ayrı bir ekran bulunur. Hangi verinin paylaşılacağına ve hukuki dayanağına her zaman hekim karar verir. Bu yazı hukuki danışmanlık değildir; kurumunuzun veri sorumlusu ile değerlendirin.",
    ],
  }),

  // ─── JURILOOP ───
  tr({
    slug: "blog-avukatlar-arasi-dava-yonlendirme",
    product: "juriloop",
    category: "JURILOOP",
    title: "Avukatlar Arası Dava Yönlendirme: İş Birliğini Kayda Almak",
    excerpt: "Uzmanlık alanı dışındaki dosyayı meslektaşa yönlendirmek yaygın ama çoğu zaman kayıtsız. Yönlendirmeyi izlenebilir kılmanın faydası.",
    body: [
      "Bir avukat, uzmanlık alanı dışındaki bir dosyayı çoğu zaman güvendiği bir meslektaşına yönlendirir. Bu yönlendirme genellikle bir telefon ya da mesajla yapılır ve kayda geçmez.",
      "Kayıtsız yönlendirmenin sorunları",
      "Müvekkilin kime yönlendirildiği, dosyanın kabul edilip edilmediği ve sürecin nerede olduğu belirsiz kalır. Müvekkil de hangi avukatla çalıştığını karıştırabilir.",
      "Meslek kurallarına dikkat",
      "Avukatlık mesleğinde iş getirme ve aracı kullanma yasakları vardır. Yönlendirme karşılığı ücret paylaşımı gibi konularda Avukatlık Kanunu'nu, TBB Meslek Kurallarını ve baronuzun yaklaşımını mutlaka kontrol edin.",
      "JuriLoop'ta nasıl işliyor?",
      "JuriLoop, hukuk profesyonelleri arasındaki dava yönlendirme ve çalışma koordinasyonunu izlenebilir biçimde ele almak için tasarlandı: yönlendirme, müvekkil kabulü, takvim ve mesajlaşma aynı çalışma alanındadır. JuriLoop Google Play'de yayındadır. Bu yazı hukuki danışmanlık değildir.",
    ],
  }),
  tr({
    slug: "blog-hukuk-burosunda-dijital-is-birligi-ve-sir-saklama",
    product: "juriloop",
    category: "JURILOOP",
    title: "Hukuk Bürosunda Dijital İş Birliği ve Sır Saklama",
    excerpt: "Avukatın sır saklama yükümlülüğü, dosya bilgisinin hangi kanaldan paylaşıldığını da kapsar. Meslektaşla çalışırken dikkat edilecekler.",
    body: [
      "Avukatlık Kanunu, avukata kendisine tevdi edilen veya görevi dolayısıyla öğrendiği bilgileri açığa vurmama yükümlülüğü getirir. Bu yükümlülük dosya bilgisinin nerede ve nasıl paylaşıldığını da ilgilendirir.",
      "Sık görülen riskler",
      "Dilekçe taslaklarının kişisel mesajlaşma gruplarında dolaşması, müvekkil belgelerinin telefon galerisinde kalması, dosyaya kimin eriştiğinin izlenememesi.",
      "Pratik ilkeler",
      "Dosya bilgisini yalnızca dosyada çalışan meslektaşla paylaşın; müvekkilin iş birliğinden haberdar olmasını sağlayın; belgeleri genel sohbetlere değil, dosyaya bağlı bir kanala koyun; iş birliği bittiğinde erişimi kapatın.",
      "JuriLoop'ta nasıl işliyor?",
      "JuriLoop, meslektaşlar arası iş birliğini dosya bağlamında tutan bir çalışma alanı sunar; mesajlaşma ve belgeler ilgili iş akışıyla ilişkilendirilir. Bu yazı genel bilgi amaçlıdır, hukuki danışmanlık değildir.",
    ],
  }),
  tr({
    slug: "blog-cmk-gorevlerini-ve-durusma-takvimini-yonetmek",
    product: "juriloop",
    category: "JURILOOP",
    title: "CMK Görevleri ve Duruşma Takvimini Tek Yerde Tutmak",
    excerpt: "Duruşma, süre ve CMK görevleri farklı yerlerde tutulunca çakışma kaçınılmaz olur. Takvimi tek kaynağa bağlamanın faydası.",
    body: [
      "Bir avukatın takvimi yalnızca duruşmalardan oluşmaz: kesin süreler, müvekkil görüşmeleri ve baro üzerinden gelen CMK görevleri de aynı güne düşer.",
      "Çakışma nereden çıkar?",
      "Duruşmalar UYAP'ta, görüşmeler telefon takviminde, CMK görevleri mesajlarda kalınca hiçbiri tek başına doğru resmi göstermez. Yoğun haftada bir sürenin kaçması ciddi sonuç doğurabilir.",
      "Tek kaynak ilkesi",
      "Tüm randevu ve sürelerin girildiği tek bir takvim olmalı; resmî kayıtlar yine UYAP'ta esas kalmak kaydıyla, günlük planlama bu tek takvimden yapılmalıdır. Yerine gidemeyeceğiniz bir iş için meslektaşa devir de aynı yerden izlenmelidir.",
      "JuriLoop'ta nasıl işliyor?",
      "JuriLoop'ta takvim, CMK ve dava yönlendirme ekranları aynı çalışma alanındadır; meslektaşa devredilen işin durumu izlenebilir. JuriLoop, UYAP'ın yerine geçmez; resmî işlemler UYAP üzerinden yürür.",
    ],
  }),
];

export const urunYazilariEn: LegacyArticle[] = [
  // ─── ECO-REPORT ───
  en({
    slug: "blog-ai-act-high-risk-delayed-two-new-prohibitions-from-december-2026",
    product: "eco-report",
    category: "AI Act",
    title: "AI Act: High-Risk Duties Delayed — But Two New Prohibitions Start on 2 December 2026",
    excerpt: "The Digital Omnibus pushed high-risk obligations to 2 December 2027. In exchange, two new prohibitions added to Article 5 start on 2 December 2026.",
    body: [
      "The general application date of the AI Act (Regulation (EU) 2024/1689) is **2 August 2026**. But the timeline is not a single date, and it **changed with Regulation (EU) 2026/1744, the Digital Omnibus.**",
      "What the timeline looks like today",
      "Chapters I and II — prohibited practices and AI literacy — have applied since **2 February 2025**. General-purpose AI and governance provisions started on **2 August 2025**.",
      "The Digital Omnibus **delayed the high-risk obligations**: to **2 December 2027** for high-risk systems under Annex III, and to **2 August 2028** for the Annex I product-safety track.",
      "A delay is not a reprieve",
      "The same amendment added **two new prohibitions** to Article 5 — points (ba) and (bb) — applying from **2 December 2026**. Prohibitions are the sharpest end of the regulation: they are not a matter of documenting and placing on the market, they are practices that **must not happen**.",
      "With these additions Article 5 now lists **10** prohibited practices. A transitional period for the marking duty under Article 50(2) also begins on the same date.",
      "Order matters: prohibition first, class second",
      "The correct sequence is: (1) does the system fall under a **prohibited practice**? (2) if not, is it **high-risk**? Annex III lists **8** areas — biometrics, critical infrastructure, education, employment, access to essential services, law enforcement, migration and border control, administration of justice. (3) if not high-risk, does a transparency obligation apply?",
      "Skipping this order produces the most expensive mistake: treating a prohibited practice as \"high-risk\" and trying to document it. A prohibited practice cannot be legitimised through documentation.",
      "The high-risk documentation load",
      "For a high-risk system, Annex IV lists **9 elements** that the technical documentation must contain: a general description of the system, the development process, monitoring and control, risk management and more. The delay does not remove this load; it moves the start date.",
      "How Nechh Eco-Report handles it",
      "The Eco-Report AI Act module asks about prohibited practice, high-risk and transparency classification in that order and produces the Annex IV technical file list. The amendment chain (2026/1744) is tracked by machine; when a question is unanswered the module does not guess, it says \"cannot decide\". Eco-Report is a preparation tool; it does not replace a conformity assessment.",
      "Source: Regulation (EU) 2024/1689 (AI Act) as amended by Regulation (EU) 2026/1744 (Digital Omnibus), EUR-Lex.",
      "Publication note: This content is general information; it is not legal advice, a conformity assessment or a company-specific compliance evaluation. The final determination rests on the official text and, where needed, legal advice.",
    ],
  }),
  en({
    slug: "blog-is-the-digital-product-passport-mandatory-not-for-any-product-yet",
    product: "eco-report",
    category: "DPP",
    title: "Is the Digital Product Passport Mandatory? Not for Any Product Yet — So When?",
    excerpt: "ESPR does not make the digital product passport mandatory for any product directly; the duty arrives through delegated acts per product group. That distinction changes buying decisions.",
    body: [
      "The most common mistake about the Digital Product Passport (DPP) is treating it as a general obligation that already applies.",
      "The accurate position: **the Ecodesign for Sustainable Products Regulation (ESPR, (EU) 2024/1781) does not make the digital product passport mandatory for any product directly.** The duty arrives through **delegated acts adopted per product group** under Article 4 (Article 9(1)-(2)).",
      "Why this matters",
      "Because the answer to a vendor saying \"the DPP is now mandatory, buy a system today\" is a question: has a delegated act been adopted **for your product group**? If not, there is no date for you either. The Eco-Report DPP module asks about delegated act status for exactly this reason and **claims no obligation** while that status is unknown.",
      "Preparation still pays",
      "Chapter III of the ESPR defines the digital product passport across **7 articles**, and Annex III lists **12 data elements** that a passport may carry. Whatever a delegated act requires will come from inside this framework, so building the data pipeline early is not wasted work.",
      "In practice the hard part is not the passport but **collecting the data from the supply chain**. Material composition, repairability and recycled content are often absent from the manufacturer's own records and have to be requested from suppliers. Starting that request after a delegated act is adopted is starting late.",
      "The ESPR also provides for a digital product passport registry; the regulation refers to **19 July 2026** for that system.",
      "What to do",
      "1) Track whether a delegated act for your product group is in the working plan. 2) Map now who will supply each Annex III data element for your product. 3) Test every \"the DPP is mandatory\" claim with the question: **under which delegated act?**",
      "How Nechh Eco-Report handles it",
      "The Eco-Report DPP module produces no obligation while the delegated act status is unknown; the default option is \"unknown\" and the module then says \"cannot decide\". Annex III data elements are produced as a readiness list. Eco-Report is a preparation tool; it does not replace an official declaration or a conformity assessment.",
      "Source: Regulation (EU) 2024/1781 (ESPR), EUR-Lex.",
      "Publication note: This content is general information; it is not legal advice, a conformity assessment or a company-specific compliance evaluation. The final determination rests on the official text and, where needed, legal advice.",
    ],
  }),
  en({
    slug: "blog-csrd-thresholds-changed-eur-450-million-and-1000-employees",
    product: "eco-report",
    category: "CSRD",
    title: "CSRD Thresholds Changed: EUR 450 million AND 1,000 Employees — What If You Are Below?",
    excerpt: "Omnibus I narrowed the CSRD scope: only undertakings exceeding both the turnover and the employee threshold report. The listed-SME obligation was deleted.",
    body: [
      "Most of the sustainability reporting thresholds in circulation are **out of date**. Directive (EU) 2026/470, known as Omnibus I, substantially narrowed the CSRD scope.",
      "The current rule",
      "Undertakings that, on their balance sheet date, exceed **both EUR 450 million in net turnover and an average of 1,000 employees** must include sustainability information in their management report. Note the **AND**: exceeding only one threshold does not create the obligation.",
      "The obligation previously foreseen for **listed SMEs (former Article 5(2)(c)) was deleted.**",
      "First reporting applies to financial years starting on or after **1 January 2027**.",
      "Below the threshold: you do not report — but the questions still arrive",
      "This is where it matters. A company below the threshold is **not required to report**; but if it sits in the value chain of a customer that is in scope, data requests will come. Most non-EU suppliers meet the CSRD this way for the first time.",
      "The directive provides a protection here: sustainability reporting standards must take account of the difficulty of gathering information from value-chain actors, especially from those **not subject** to the reporting requirements. A cap is foreseen on what may be requested from undertakings that do not exceed **1,000 employees**.",
      "The practical consequence: a customer in scope cannot request unlimited data from you. Whether an incoming request fits within that cap is a question you are entitled to ask.",
      "The ESRS standards",
      "The content of the reporting is set by the European Sustainability Reporting Standards; the delegated regulation in force lists **12 standards** (ESRS 1 and 2 are general, the rest cover environmental, social and governance topics).",
      "Why working from old thresholds is dangerous",
      "An assessment made with superseded thresholds sells an obligation to a company that does not have one. That is not only unnecessary cost but a misstatement risk. A threshold looks like a number, but it depends on **which version of the text it was read from**.",
      "How Nechh Eco-Report handles it",
      "The Eco-Report CSRD module reads the thresholds from the Omnibus I text and assesses the value-chain protection and the out-of-scope case separately. Legislative change is tracked by machine. Eco-Report is a preparation tool; it does not replace an audit or an official declaration.",
      "Source: Directive (EU) 2022/2464 (CSRD), Directive (EU) 2026/470 (Omnibus I) and Delegated Regulation (EU) 2023/2772 (ESRS), EUR-Lex.",
      "Publication note: This content is general information; it is not legal advice, a conformity assessment or a company-specific compliance evaluation. The final determination rests on the official text and, where needed, legal advice.",
    ],
  }),
  en({
    slug: "blog-what-is-the-cra-are-non-eu-software-makers-in-scope",
    product: "eco-report",
    category: "CRA",
    title: "What Is the Cyber Resilience Act? Are Non-EU Software Makers in Scope?",
    excerpt: "The CRA applies to products with digital elements placed on the EU market and does not require the manufacturer to be established in the EU. Reporting duties have applied since 11 September 2026.",
    body: [
      "The Cyber Resilience Act (CRA) sets cybersecurity requirements for **products with digital elements** placed on the EU market. \"Products with digital elements\" covers software, not only hardware.",
      "Who is in scope?",
      "The regulation does not require the manufacturer to be established in the EU. If the product enters the EU market, obligations are shared between manufacturer, importer and distributor. In practice: **a software manufacturer established outside the EU is directly in scope if it sells into the EU.**",
      "This differs from DORA, where the obligation sits with the EU financial entity and reaches the supplier through the **contract**. Under the CRA the duty comes straight from the regulation.",
      "Timeline — one duty already applies",
      "The general application date is **11 December 2027**. There are two exceptions: Chapter IV on notified bodies applies from **11 June 2026**, and **Article 14 has applied since 11 September 2026**.",
      "So the clock is already running for actively exploited vulnerabilities and severe incidents: 24 hours for the early warning, 72 hours for the notification, 14 days for the final report.",
      "Are you out of scope?",
      "The regulation does not apply to products covered by the medical device, in vitro diagnostic and motor vehicle regulations, to products certified under civil aviation rules, to marine equipment, to spare parts manufactured to the same specifications as the components they replace, or to products developed exclusively for national security or defence.",
      "Regulation (EU) 2025/327 (European Health Data Space) also amended the CRA: products classified as **EHR systems** demonstrate conformity through the procedure in that regulation. This takes precedence over the product class.",
      "Product class determines the conformity route",
      "Annex III splits important products into two classes (19 items in class I, 4 in class II) and lists 3 critical products. If your product is on none of these lists it counts as \"other\"; **the Annex I requirements still apply**, only the conformity route is more flexible.",
      "One point to watch: for class I important products, if harmonised standards were not applied or only applied in part, the internal control route closes and a route involving a third party must be used.",
      "Three separate work packages",
      "The CRA asks for three different things at once: the **13 product requirements** in Annex I Part I, the **8 vulnerability handling requirements** in Annex I Part II, and the **8-element technical documentation** in Annex VII. These do not substitute for one another: a secure product without a vulnerability handling process is not conformant.",
      "Support period",
      "The manufacturer must determine a support period and state it clearly to users. The floor is **at least 5 years**, and a security update must remain available for **at least 10 years** after it is issued. The period follows the product's expected lifetime: you cannot go below the floor, and for long-lived products the floor may not be enough.",
      "How Nechh Eco-Report handles it",
      "The Eco-Report CRA module assesses product class, conformity route and support period from data parsed out of the official text; when a question is unanswered it does not guess, it says \"cannot decide\". The CRA Manufacturer Readiness Kit turns Annexes I, III and VII into working files. Eco-Report is a preparation tool; it does not replace a conformity assessment or CE marking.",
      "Source: Regulation (EU) 2024/2847 (Cyber Resilience Act), EUR-Lex; amended by Regulation (EU) 2025/327.",
      "Publication note: This content is general information; it is not legal advice, a conformity assessment or a company-specific compliance evaluation. The final determination rests on the official text and, where needed, legal advice.",
    ],
  }),
  en({
    slug: "blog-cra-article-14-reporting-clock-already-running",
    product: "eco-report",
    category: "CRA",
    title: "CRA Article 14: The 24/72-Hour Reporting Clock Has Been Running Since 11 September 2026",
    excerpt: "Most of the CRA starts on 11 December 2027, but the reporting duty has applied since 11 September 2026. When does the clock start?",
    body: [
      "Most of Regulation (EU) 2024/2847 starts to apply on **11 December 2027**. The text itself carves out an exception: **Article 14 applies from 11 September 2026**.",
      "For manufacturers placing products with digital elements on the EU market this means: while there is still time for the Annex I requirements and the technical documentation, **the reporting duty applies today.**",
      "The deadlines",
      "For an actively exploited vulnerability: an early warning within **24 hours** of becoming aware, a notification within **72 hours**, and a final report within **14 days**. For a severe incident the regulation sets the final report at one month.",
      "Reports go to the CSIRT designated as coordinator and to ENISA.",
      "When does the clock start?",
      "The period starts when the manufacturer **becomes aware**. The real question is therefore organisational rather than technical: who records the moment of awareness, and where? Which address receives vulnerability reports, and who reads it at the weekend?",
      "A team without a procedure will debate these questions during the incident. The clock keeps running meanwhile.",
      "What has to be written down in advance",
      "Who decides whether to report, who writes the report, who performs the technical review — and who **backs up** each of them. A procedure that depends on one person does not work on holidays or outside office hours; the deadlines do not wait.",
      "The coordinated vulnerability disclosure contact point and the system that records the awareness timestamp also have to be fixed in advance.",
      "Reporting alone is not enough",
      "Annex I Part II also requires public disclosure of fixed vulnerabilities, distribution of security updates **separately** from functionality updates where technically feasible, and a machine-readable software bill of materials covering at least the top-level dependencies. That part contains 8 process requirements in total.",
      "How Nechh Eco-Report handles it",
      "The CRA Manufacturer Readiness Kit includes a notification procedure template for Article 14: the deadlines come from the regulation text, while the clock-zero definition, roles, backups and incident log fields are left to be filled in. No deadline that is not in the regulation has been added to the template.",
      "Source: Regulation (EU) 2024/2847 (Cyber Resilience Act), EUR-Lex; amended by Regulation (EU) 2025/327.",
      "Publication note: This content is general information; it is not legal advice, a conformity assessment or a company-specific compliance evaluation. The final determination rests on the official text and, where needed, legal advice.",
    ],
  }),
  en({
    slug: "blog-cbam-default-values-corrected-2026-1740",
    product: "eco-report",
    category: "CBAM",
    title: "CBAM Default Values Corrected: What Did 2026/1740 Change?",
    excerpt: "The Commission corrected the default value tables with a separate regulation, applied retroactively from 1 January 2026. Which rows were affected?",
    body: [
      "The European Commission corrected the annexes of Implementing Regulation (EU) 2025/2621, which sets CBAM default values, through Implementing Regulation (EU) 2026/1740. It was published in the Official Journal on 31 July 2026 and applies from 1 January 2026.",
      "Why it matters",
      "Because the correction came as a separate regulation, anyone checking only the 2025/2621 page may miss it. Every calculation that uses default values should confirm which version of the tables it relies on.",
      "What changed",
      "Certain rows in Annex I and Annex IV were corrected. The change is small for some country-product rows and large for others; for example, the Tunisia rows and CN subheading 7616 99 in Annex IV show clear differences. For Türkiye, the total value for 7208 51 20 (hot-rolled flat steel) did not change.",
      "Status in Nechh Eco-Report",
      "Eco-Report's default value tables were updated with the 2026/1740 correction on 14 September 2026. The regulation behind each default value is shown next to it. Eco-Report is a preparation tool; official verification is carried out only by an accredited verifier.",
      "Sources: Commission Implementing Regulation (EU) 2026/1740 (correcting act) and (EU) 2025/2621, EUR-Lex.",
    ],
  }),
  en({
    slug: "blog-cbam-what-exporters-pay-without-real-data",
    product: "eco-report",
    category: "CBAM",
    title: "What Does an Exporter Pay Without Real Data? The CBAM Default Value Mark-Up",
    excerpt: "If your EU buyer cannot get actual emissions data, it must use the default value plus a mark-up. The difference triples from 2026 to 2028.",
    body: [
      "Under CBAM the declaration is made by the EU importer; a non-EU exporter does not declare, it supplies data. If the importer cannot obtain actual emissions data from the producer, it must use the default value published by the EU.",
      "The mark-up on the default value",
      "Under Implementing Regulation (EU) 2025/2621, a mark-up of 10% for 2026, 20% for 2027 and 30% from 2028 applies to default values for steel, aluminium, cement and hydrogen. For fertilisers the rate is 1%.",
      "A worked example",
      "For CN 7208 51 20, origin Türkiye, 1,000 tonnes, with a certificate price of €75.28, the cost of the gap between the default value and actual data is roughly €18,278 in 2026, €36,556 in 2027 and €54,834 in 2028. This is an example; your product's figure is calculated from your own data. The certificate price follows the EU ETS and changes.",
      "Who carries the difference?",
      "The importer pays, but the cost usually comes back to the exporter in price negotiations, or the buyer switches supplier.",
      "How Nechh Eco-Report handles it",
      "In Eco-Report, entering the origin country, CN code, year and tonnage shows the official default value and the value including the mark-up side by side. Calculations with actual data follow the EU method, and every figure shows its source.",
    ],
  }),
  en({
    slug: "blog-cbam-50-tonne-exemption-whose-tonnage-counts",
    product: "eco-report",
    category: "CBAM",
    title: "The CBAM 50-Tonne Exemption: Whose Tonnage Counts?",
    excerpt: "\"We sell less than 50 tonnes a year, so it doesn't apply to us\" is often wrong. The threshold looks at the EU importer's total, not your sales.",
    body: [
      "Regulation (EU) 2025/2083 added a mass threshold to CBAM: if an EU importer's annual total net mass of covered goods is 50 tonnes or less, no CBAM obligation arises.",
      "Whose tonnage is counted?",
      "The threshold looks at the importer's total purchases from all suppliers in a year, not at a single exporter's sales. A buyer ordering 20 tonnes from you but 200 tonnes elsewhere is well above it.",
      "Exceptions",
      "Electricity and hydrogen are not covered by this exemption. Nor does it apply automatically; the importer states it in the customs declaration.",
      "What to do",
      "Ask your buyer about their total CBAM tonnage and whether they will need data from you. If they do, the first annual declaration for 2026 imports is due by 30 September 2027, so preparation should not be left to the last month.",
      "How Nechh Eco-Report handles it",
      "In Eco-Report the exemption check runs as soon as the tonnage is entered. If you are exempt it says so clearly; if not, you move on to the actual-data calculation.",
    ],
  }),

  // ─── HELIALOOP ───
  en({
    slug: "blog-why-whatsapp-is-not-enough-for-patient-referrals",
    product: "helialoop",
    category: "HELIALOOP",
    title: "Why WhatsApp Is Not Enough for Patient Referrals",
    excerpt: "Referring a patient to a colleague often starts with a message and gets lost there. Where referrals break down and what a structured flow changes.",
    body: [
      "When a physician refers a patient to another specialty, it usually starts with a message to a colleague they know. The message is read, the patient is called or not, and the referring physician rarely learns the outcome.",
      "Where referrals get lost",
      "The referral is buried among personal chats. Nobody knows whether the patient booked. Who referred which patient, and why, cannot be seen as a whole. Patient data is scattered across personal messaging apps.",
      "What a structured flow changes",
      "When a referral is kept as its own record, both the referring and receiving physician can see which step it is at. Clear next steps and responsibilities make it less likely that the patient falls through the gap.",
      "How HeliaLoop handles it",
      "HeliaLoop is designed to bring referral and appointment coordination between physicians and clinicians into one workspace: finding colleagues, creating and tracking referrals, messaging and availability are part of the same flow. HeliaLoop is available on Google Play.",
    ],
  }),
  en({
    slug: "blog-what-a-good-referral-note-should-contain",
    product: "helialoop",
    category: "HELIALOOP",
    title: "What Should a Good Referral Note Contain?",
    excerpt: "An incomplete referral note sends the patient through the same tests twice. The information a colleague needs at first glance.",
    body: [
      "The receiving physician's first minute is often spent asking \"why was this patient sent to me?\". A short but complete referral note saves time and spares the patient repeated tests.",
      "Core items",
      "The reason for referral and the question to be answered; relevant history and current diagnoses; medications and allergies; results and dates of tests already done; urgency; the referring physician's contact details.",
      "Closing the loop",
      "A referral does not end when the patient arrives. Sending the receiving physician's assessment back to the referrer keeps care continuous and builds trust between colleagues.",
      "Proportion in data sharing",
      "Health data is a special category of personal data. Share only what the referral needs, and do not leave it scattered in personal messaging apps.",
      "How HeliaLoop handles it",
      "In HeliaLoop a referral is created and tracked as its own record, and both physicians can see which step it is at. This article is general information, not clinical or legal advice.",
    ],
  }),
  en({
    slug: "blog-protecting-patient-data-in-physician-collaboration",
    product: "helialoop",
    category: "HELIALOOP",
    title: "Protecting Patient Data in Physician Collaboration",
    excerpt: "Health data is a special category of personal data. Principles to keep in mind when sharing it with a colleague.",
    body: [
      "Data protection laws such as Türkiye's KVKK (Law No. 6698) and the EU GDPR treat health data as a special category and attach strict conditions to processing it. A referral between colleagues is also a data transfer.",
      "Three core principles",
      "Necessity: share only what the referral requires. Legal basis: the transfer must rest on the patient's consent or a statutory exception. Security: data should not be scattered in personal photo galleries and general messaging groups.",
      "The risk of personal messaging",
      "A lab result photo sent in a general-purpose messaging app ends up in phone backups, the gallery and sometimes other chats. Who accessed which data cannot be traced afterwards.",
      "How HeliaLoop handles it",
      "HeliaLoop keeps referrals and messaging in a workspace dedicated to physicians, with a separate screen for patient consent. The physician always decides what is shared and on what legal basis. This article is not legal advice; review it with your organisation's data controller.",
    ],
  }),

  // ─── JURILOOP ───
  en({
    slug: "blog-case-referrals-between-lawyers",
    product: "juriloop",
    category: "JURILOOP",
    title: "Case Referrals Between Lawyers: Putting Collaboration on Record",
    excerpt: "Referring a matter outside your practice area to a colleague is common but usually unrecorded. Why a traceable referral helps.",
    body: [
      "Lawyers often refer a matter outside their practice area to a colleague they trust. The referral is usually made by phone or message and never recorded.",
      "Problems with unrecorded referrals",
      "It stays unclear who the client was referred to, whether the matter was accepted and where it stands. The client may also be unsure which lawyer they are working with.",
      "Mind the professional rules",
      "The legal profession has rules against soliciting work and using intermediaries. On questions such as fee sharing for referrals, always check the applicable legislation, your bar's rules of conduct and its guidance.",
      "How JuriLoop handles it",
      "JuriLoop is designed to make case referrals and working coordination between legal professionals traceable: referrals, client acceptance, the calendar and messaging sit in one workspace. JuriLoop is available on Google Play. This article is not legal advice.",
    ],
  }),
  en({
    slug: "blog-digital-collaboration-and-confidentiality-in-law-firms",
    product: "juriloop",
    category: "JURILOOP",
    title: "Digital Collaboration and Confidentiality in Law Firms",
    excerpt: "A lawyer's duty of confidentiality also covers the channel through which case information is shared. What to watch when working with colleagues.",
    body: [
      "Lawyers are bound not to disclose information entrusted to them or learned in the course of their work. That duty also concerns where and how case information is shared.",
      "Common risks",
      "Draft pleadings circulating in personal messaging groups, client documents left in phone galleries, and no way of tracing who accessed a file.",
      "Practical principles",
      "Share case information only with the colleague working on the matter; make sure the client knows about the collaboration; put documents in a channel tied to the case rather than general chats; close access when the collaboration ends.",
      "How JuriLoop handles it",
      "JuriLoop offers a workspace that keeps collaboration between colleagues in the context of the case; messages and documents are linked to the relevant workflow. This article is general information, not legal advice.",
    ],
  }),
  en({
    slug: "blog-managing-court-dates-and-duty-assignments-in-one-place",
    product: "juriloop",
    category: "JURILOOP",
    title: "Keeping Court Dates and Duty Assignments in One Place",
    excerpt: "When hearings, deadlines and legal-aid duties live in different places, clashes are inevitable. The benefit of a single calendar.",
    body: [
      "A lawyer's calendar is not just hearings: statutory deadlines, client meetings and legal-aid (CMK) duties assigned through the bar land on the same days.",
      "Where clashes come from",
      "When hearings are in the court system, meetings in the phone calendar and duty assignments in messages, none of them shows the real picture. In a busy week a missed deadline can have serious consequences.",
      "The single-source principle",
      "There should be one calendar where every appointment and deadline is entered; official records remain in the court system, but day-to-day planning is done from this single calendar. Work handed over to a colleague should be tracked from the same place.",
      "How JuriLoop handles it",
      "In JuriLoop the calendar, legal-aid duty and case referral screens sit in the same workspace, and the status of work handed to a colleague can be tracked. JuriLoop does not replace UYAP, Türkiye's court information system; official filings go through UYAP.",
    ],
  }),
];
