/** Ürün yazıları — 18 Eyl 2026. HeliaLoop, JuriLoop ve Eco-Report için 3'er yazı, TR ve EN (Hasan: yalnızca bu üçü).
 *  KURAL: yazılarda ürün hakkında yalnızca doğrulanmış özellik anlatılır
 *  (kaynak: TONSORA-OZELLIKLER.md, PALETRA/MAGAZA-METINLERI.md, Eco-Report SAHA-KITAPCIGI.md, site.ts ürün metinleri).
 *  Yasaklı ifadeler: "Türkiye'nin ilk", "otomatik hatırlatma", SMS, "resmî/AB onaylı rapor", mağazada olmayan uygulama için "indir". */
import type { LegacyArticle } from "./legacyArticles";

const TARIH = "2026-09-18";

type Taslak = Omit<LegacyArticle, "path" | "date">;

const tr = (a: Taslak): LegacyArticle => ({ ...a, path: `/blog/${a.slug}`, date: TARIH });
const en = (a: Taslak): LegacyArticle => ({ ...a, path: `/en/blog/${a.slug}`, date: TARIH });

export const urunYazilariTr: LegacyArticle[] = [
  // ─── ECO-REPORT ───
  tr({
    slug: "blog-cbam-varsayilan-degerler-2026-1740-duzeltmesi",
    product: "eco-report",
    category: "CBAM",
    title: "CBAM Varsayılan Değerleri Düzeltildi: 2026/1740 Ne Değiştirdi?",
    excerpt: "Komisyon, varsayılan değer tablolarını ayrı bir düzeltme tüzüğüyle güncelledi ve 1 Ocak 2026'ya geriye dönük uyguladı. Hangi satırlar etkilendi?",
    body: [
      "AB Komisyonu, CBAM varsayılan değerlerini belirleyen 2025/2621 sayılı Uygulama Tüzüğü'nün eklerini 2026/1740 sayılı Uygulama Tüzüğü ile düzeltti. Metin 31 Temmuz 2026'da AB Resmî Gazetesi'nde yayımlandı ve 1 Ocak 2026'dan itibaren geçerli olacak şekilde uygulanıyor.",
      "Neden dikkat edilmeli?",
      "Düzeltme ayrı bir tüzükle geldiği için 2025/2621'in kendi sayfasına bakan biri değişikliği göremeyebilir. Varsayılan değer kullanan her hesap, hangi tablo sürümüne dayandığını kontrol etmelidir.",
      "Ne değişti?",
      "Ek I ve Ek IV'teki bazı satırlar düzeltildi. Değişiklik bazı ülke-ürün satırlarında küçük, bazılarında büyüktür; örneğin Tunus satırlarında ve Ek IV'teki 7616 99 alt başlığında belirgin farklar var. Türkiye için 7208 51 20 (sıcak haddelenmiş yassı çelik) satırında toplam değer değişmedi.",
      "Nechh Eco-Report'ta durum",
      "Eco-Report'taki varsayılan değer tabloları 14 Eylül 2026'da 2026/1740 düzeltmesiyle güncellendi. Uygulamada her varsayılan değerin yanında dayandığı tüzük gösterilir. Eco-Report bir hazırlık aracıdır; resmî doğrulama yalnızca akredite doğrulayıcı tarafından yapılır.",
      "Kaynak: Commission Implementing Regulation (EU) 2026/1740 (correcting act) ve (EU) 2025/2621, EUR-Lex.",
    ],
  }),
  tr({
    slug: "blog-cbam-veri-vermeyen-ihracatci-ne-oder-cezali-ek",
    product: "eco-report",
    category: "CBAM",
    title: "Veri Vermeyen İhracatçı Ne Öder? CBAM Varsayılan Değerine Eklenen Pay",
    excerpt: "AB'deki alıcınız gerçek emisyon verisi alamazsa varsayılan değeri, üstüne eklenen payla birlikte kullanır. Fark 2026'dan 2028'e üç katına çıkar.",
    body: [
      "CBAM'de beyanı AB'deki ithalatçı verir; Türk ihracatçı beyan vermez, veri verir. İthalatçı üreticiden gerçek emisyon verisi alamazsa AB'nin yayımladığı varsayılan değeri kullanmak zorundadır.",
      "Varsayılan değerin üstüne eklenen pay",
      "2025/2621 sayılı Uygulama Tüzüğü'ne göre çelik, alüminyum, çimento ve hidrojende varsayılan değere 2026 için %10, 2027 için %20, 2028 ve sonrası için %30 ek uygulanır. Gübrede bu oran %1'dir.",
      "Rakamla bir örnek",
      "CN 7208 51 20, menşe Türkiye, 1.000 ton için varsayılan değer ile gerçek veri arasındaki farkın maliyeti, sertifika fiyatı €75,28 alındığında yaklaşık 2026'da €18.278, 2027'de €36.556, 2028'de €54.834'tür. Bu bir örnektir; sizin ürününüzün rakamı kendi verinizle hesaplanır. Sertifika fiyatı AB ETS'ye bağlı olduğundan değişir.",
      "Fark kime yansır?",
      "Maliyeti ithalatçı öder ama genellikle fiyat pazarlığında ihracatçıya geri döner ya da alıcı tedarikçi değiştirir.",
      "Nechh Eco-Report'ta nasıl işliyor?",
      "Eco-Report'ta menşe ülke, CN kodu, yıl ve tonaj girildiğinde resmî varsayılan değer ve ek dahil hali yan yana gösterilir. Gerçek veriyle hesap AB yöntemine göre yapılır ve her rakamın yanında kaynağı yazar.",
    ],
  }),
  tr({
    slug: "blog-cbam-50-ton-muafiyeti-kimin-tonaji-sayilir",
    product: "eco-report",
    category: "CBAM",
    title: "CBAM'de 50 Ton Muafiyeti: Kimin Tonajı Sayılır?",
    excerpt: "\"Yılda 50 tondan az satıyoruz, bizi ilgilendirmez\" cümlesi çoğu zaman yanlış. Sınır sizin satışınıza değil, AB'deki ithalatçının toplamına bakar.",
    body: [
      "2025/2083 sayılı Tüzük ile CBAM'e bir kütle eşiği eklendi: AB'deki bir ithalatçının kapsamdaki mallardan yıllık toplam net kütlesi 50 ton veya altındaysa CBAM yükümlülüğü doğmaz.",
      "Sınır kimin tonajına bakar?",
      "Eşik, ihracatçının tek satışına değil, ithalatçının bir yıl içinde tüm tedarikçilerinden yaptığı toplam alıma bakar. Size 20 ton sipariş veren alıcı başka yerlerden 200 ton alıyorsa eşiği çoktan aşmıştır.",
      "İstisnalar",
      "Elektrik ve hidrojen bu muafiyete girmez. Muafiyet kendiliğinden de işlemez; ithalatçı bunu gümrük beyanında belirtir.",
      "Ne yapmalı?",
      "Alıcınıza toplam CBAM tonajını ve sizden veri isteyip istemeyeceğini sorun. Veri isteniyorsa ilk yıllık beyan 2026 ithalatları için 30 Eylül 2027'ye kadar verilir; hazırlığı son aya bırakmamak gerekir.",
      "Nechh Eco-Report'ta nasıl işliyor?",
      "Eco-Report'ta tonaj girildiğinde muafiyet kontrolü anında yapılır. Muafsanız bunu açıkça söyler; muaf değilseniz gerçek veriyle hesap adımlarına geçilir.",
    ],
  }),

  // ─── HELIALOOP ───
  tr({
    slug: "blog-hasta-sevkinde-whatsapp-neden-yetmiyor",
    product: "helialoop",
    category: "HELIALOOP",
    title: "Hasta Sevkinde WhatsApp Neden Yetmiyor?",
    excerpt: "Meslektaşa hasta yönlendirmek çoğu zaman bir mesajla başlar ve orada kaybolur. Yönlendirmenin kayıp noktaları ve düzenli bir akışın faydası.",
    body: [
      "Bir hekim hastasını başka bir branşa yönlendirirken çoğu zaman bildiği bir meslektaşa mesaj atar. Mesaj okunur, hasta aranır ya da aranmaz; ilk hekim sonucu çoğu zaman öğrenemez.",
      "Kayıp noktaları",
      "Yönlendirme kaydı kişisel sohbetlerin arasında kaybolur. Hastanın randevu alıp almadığı bilinmez. Kim, hangi hastayı, hangi gerekçeyle yönlendirdi sorusunun cevabı toplu olarak görülemez. Hasta verisi de kişisel mesajlaşma uygulamalarında dağınık kalır.",
      "Düzenli bir akış neyi değiştirir?",
      "Yönlendirme ayrı bir kayıt olarak tutulduğunda hem gönderen hem alan hekim sürecin hangi adımda olduğunu görür. Sonraki adımın ve sorumluluğun netleşmesi, hastanın arada kaybolma ihtimalini düşürür.",
      "HeliaLoop'ta nasıl işliyor?",
      "HeliaLoop, hekimler ve klinisyenler arasındaki yönlendirme ve randevu koordinasyonunu tek bir çalışma alanında toplamak için tasarlandı: meslektaş arama, yönlendirme oluşturma ve takip, mesajlaşma ve müsaitlik ekranları bu akışın parçasıdır. HeliaLoop Google Play'de yayındadır.",
    ],
  }),
  tr({
    slug: "blog-sevk-notunda-olmasi-gerekenler",
    product: "helialoop",
    category: "HELIALOOP",
    title: "İyi Bir Sevk Notunda Neler Olmalı?",
    excerpt: "Eksik sevk notu hastayı ikinci kez aynı tetkiklere sokar. Meslektaşın ilk bakışta ihtiyaç duyduğu bilgiler.",
    body: [
      "Yönlendirilen hekimin ilk dakikası çoğu zaman \"bu hasta neden bana geldi?\" sorusuyla geçer. Kısa ama eksiksiz bir sevk notu hem zamanı hem hastanın tekrar tetkik yükünü azaltır.",
      "Temel başlıklar",
      "Yönlendirme gerekçesi ve beklenen soru; ilgili öykü ve mevcut tanılar; kullanılan ilaçlar ve alerjiler; yapılmış tetkiklerin sonuçları ve tarihleri; aciliyet derecesi; gönderen hekimin iletişim bilgisi.",
      "Geri bildirim döngüsü",
      "Sevk, hasta karşı tarafa ulaşınca bitmez. Alan hekimin değerlendirmesini gönderene iletmesi, hastanın bakımında sürekliliği sağlar ve meslektaşlar arası güveni artırır.",
      "Veri paylaşımında ölçü",
      "Sağlık verisi özel nitelikli kişisel veridir. Yalnızca yönlendirme için gerekli olan bilgi paylaşılmalı, kişisel mesajlaşma uygulamalarında dağınık bırakılmamalıdır.",
      "HeliaLoop'ta nasıl işliyor?",
      "HeliaLoop'ta yönlendirme ayrı bir kayıt olarak oluşturulur ve takip edilir; iki hekim de sürecin hangi adımda olduğunu görür. Bu yazı genel bilgi amaçlıdır, klinik veya hukuki tavsiye değildir.",
    ],
  }),
  tr({
    slug: "blog-hekimler-arasi-is-birliginde-hasta-verisi",
    product: "helialoop",
    category: "HELIALOOP",
    title: "Hekimler Arası İş Birliğinde Hasta Verisini Korumak",
    excerpt: "Sağlık verisi özel nitelikli kişisel veridir. Meslektaşla paylaşırken hangi ilkeler akılda tutulmalı?",
    body: [
      "6698 sayılı KVKK, sağlık verisini özel nitelikli kişisel veri olarak sayar ve işlenmesini sıkı şartlara bağlar. Meslektaşlar arası yönlendirme de bir veri paylaşımıdır.",
      "Üç temel ilke",
      "Gereklilik: yalnızca yönlendirme için gereken bilgi paylaşılmalıdır. Hukuki dayanak: paylaşım, hastanın onamına ya da kanundaki bir istisnaya dayanmalıdır. Güvenlik: veri kişisel telefon galerilerinde ve genel mesajlaşma gruplarında dağınık kalmamalıdır.",
      "Kişisel mesajlaşmanın riski",
      "Genel amaçlı mesajlaşma uygulamasında gönderilen tahlil fotoğrafı telefon yedeğine, galeriye ve bazen başka sohbetlere taşınır. Kimin hangi veriye eriştiği sonradan izlenemez.",
      "HeliaLoop'ta nasıl işliyor?",
      "HeliaLoop, yönlendirme ve mesajlaşmayı hekimlere özel bir çalışma alanında toplar; hasta onamı için ayrı bir ekran bulunur. Hangi verinin paylaşılacağına ve hukuki dayanağına her zaman hekim karar verir. Bu yazı hukuki danışmanlık değildir; kurumunuzun veri sorumlusu ile değerlendirin.",
    ],
  }),

  // ─── JURILOOP ───
  tr({
    slug: "blog-avukatlar-arasi-dava-yonlendirme",
    product: "juriloop",
    category: "JURILOOP",
    title: "Avukatlar Arası Dava Yönlendirme: İş Birliğini Kayda Almak",
    excerpt: "Uzmanlık alanı dışındaki dosyayı meslektaşa yönlendirmek yaygın ama çoğu zaman kayıtsız. Yönlendirmeyi izlenebilir kılmanın faydası.",
    body: [
      "Bir avukat, uzmanlık alanı dışındaki bir dosyayı çoğu zaman güvendiği bir meslektaşına yönlendirir. Bu yönlendirme genellikle bir telefon ya da mesajla yapılır ve kayda geçmez.",
      "Kayıtsız yönlendirmenin sorunları",
      "Müvekkilin kime yönlendirildiği, dosyanın kabul edilip edilmediği ve sürecin nerede olduğu belirsiz kalır. Müvekkil de hangi avukatla çalıştığını karıştırabilir.",
      "Meslek kurallarına dikkat",
      "Avukatlık mesleğinde iş getirme ve aracı kullanma yasakları vardır. Yönlendirme karşılığı ücret paylaşımı gibi konularda Avukatlık Kanunu'nu, TBB Meslek Kurallarını ve baronuzun yaklaşımını mutlaka kontrol edin.",
      "JuriLoop'ta nasıl işliyor?",
      "JuriLoop, hukuk profesyonelleri arasındaki dava yönlendirme ve çalışma koordinasyonunu izlenebilir biçimde ele almak için tasarlandı: yönlendirme, müvekkil kabulü, takvim ve mesajlaşma aynı çalışma alanındadır. JuriLoop Google Play'de yayındadır. Bu yazı hukuki danışmanlık değildir.",
    ],
  }),
  tr({
    slug: "blog-hukuk-burosunda-dijital-is-birligi-ve-sir-saklama",
    product: "juriloop",
    category: "JURILOOP",
    title: "Hukuk Bürosunda Dijital İş Birliği ve Sır Saklama",
    excerpt: "Avukatın sır saklama yükümlülüğü, dosya bilgisinin hangi kanaldan paylaşıldığını da kapsar. Meslektaşla çalışırken dikkat edilecekler.",
    body: [
      "Avukatlık Kanunu, avukata kendisine tevdi edilen veya görevi dolayısıyla öğrendiği bilgileri açığa vurmama yükümlülüğü getirir. Bu yükümlülük dosya bilgisinin nerede ve nasıl paylaşıldığını da ilgilendirir.",
      "Sık görülen riskler",
      "Dilekçe taslaklarının kişisel mesajlaşma gruplarında dolaşması, müvekkil belgelerinin telefon galerisinde kalması, dosyaya kimin eriştiğinin izlenememesi.",
      "Pratik ilkeler",
      "Dosya bilgisini yalnızca dosyada çalışan meslektaşla paylaşın; müvekkilin iş birliğinden haberdar olmasını sağlayın; belgeleri genel sohbetlere değil, dosyaya bağlı bir kanala koyun; iş birliği bittiğinde erişimi kapatın.",
      "JuriLoop'ta nasıl işliyor?",
      "JuriLoop, meslektaşlar arası iş birliğini dosya bağlamında tutan bir çalışma alanı sunar; mesajlaşma ve belgeler ilgili iş akışıyla ilişkilendirilir. Bu yazı genel bilgi amaçlıdır, hukuki danışmanlık değildir.",
    ],
  }),
  tr({
    slug: "blog-cmk-gorevlerini-ve-durusma-takvimini-yonetmek",
    product: "juriloop",
    category: "JURILOOP",
    title: "CMK Görevleri ve Duruşma Takvimini Tek Yerde Tutmak",
    excerpt: "Duruşma, süre ve CMK görevleri farklı yerlerde tutulunca çakışma kaçınılmaz olur. Takvimi tek kaynağa bağlamanın faydası.",
    body: [
      "Bir avukatın takvimi yalnızca duruşmalardan oluşmaz: kesin süreler, müvekkil görüşmeleri ve baro üzerinden gelen CMK görevleri de aynı güne düşer.",
      "Çakışma nereden çıkar?",
      "Duruşmalar UYAP'ta, görüşmeler telefon takviminde, CMK görevleri mesajlarda kalınca hiçbiri tek başına doğru resmi göstermez. Yoğun haftada bir sürenin kaçması ciddi sonuç doğurabilir.",
      "Tek kaynak ilkesi",
      "Tüm randevu ve sürelerin girildiği tek bir takvim olmalı; resmî kayıtlar yine UYAP'ta esas kalmak kaydıyla, günlük planlama bu tek takvimden yapılmalıdır. Yerine gidemeyeceğiniz bir iş için meslektaşa devir de aynı yerden izlenmelidir.",
      "JuriLoop'ta nasıl işliyor?",
      "JuriLoop'ta takvim, CMK ve dava yönlendirme ekranları aynı çalışma alanındadır; meslektaşa devredilen işin durumu izlenebilir. JuriLoop, UYAP'ın yerine geçmez; resmî işlemler UYAP üzerinden yürür.",
    ],
  }),
];

export const urunYazilariEn: LegacyArticle[] = [
  // ─── ECO-REPORT ───
  en({
    slug: "blog-cbam-default-values-corrected-2026-1740",
    product: "eco-report",
    category: "CBAM",
    title: "CBAM Default Values Corrected: What Did 2026/1740 Change?",
    excerpt: "The Commission corrected the default value tables with a separate regulation, applied retroactively from 1 January 2026. Which rows were affected?",
    body: [
      "The European Commission corrected the annexes of Implementing Regulation (EU) 2025/2621, which sets CBAM default values, through Implementing Regulation (EU) 2026/1740. It was published in the Official Journal on 31 July 2026 and applies from 1 January 2026.",
      "Why it matters",
      "Because the correction came as a separate regulation, anyone checking only the 2025/2621 page may miss it. Every calculation that uses default values should confirm which version of the tables it relies on.",
      "What changed",
      "Certain rows in Annex I and Annex IV were corrected. The change is small for some country-product rows and large for others; for example, the Tunisia rows and CN subheading 7616 99 in Annex IV show clear differences. For Türkiye, the total value for 7208 51 20 (hot-rolled flat steel) did not change.",
      "Status in Nechh Eco-Report",
      "Eco-Report's default value tables were updated with the 2026/1740 correction on 14 September 2026. The regulation behind each default value is shown next to it. Eco-Report is a preparation tool; official verification is carried out only by an accredited verifier.",
      "Sources: Commission Implementing Regulation (EU) 2026/1740 (correcting act) and (EU) 2025/2621, EUR-Lex.",
    ],
  }),
  en({
    slug: "blog-cbam-what-exporters-pay-without-real-data",
    product: "eco-report",
    category: "CBAM",
    title: "What Does an Exporter Pay Without Real Data? The CBAM Default Value Mark-Up",
    excerpt: "If your EU buyer cannot get actual emissions data, it must use the default value plus a mark-up. The difference triples from 2026 to 2028.",
    body: [
      "Under CBAM the declaration is made by the EU importer; a non-EU exporter does not declare, it supplies data. If the importer cannot obtain actual emissions data from the producer, it must use the default value published by the EU.",
      "The mark-up on the default value",
      "Under Implementing Regulation (EU) 2025/2621, a mark-up of 10% for 2026, 20% for 2027 and 30% from 2028 applies to default values for steel, aluminium, cement and hydrogen. For fertilisers the rate is 1%.",
      "A worked example",
      "For CN 7208 51 20, origin Türkiye, 1,000 tonnes, with a certificate price of €75.28, the cost of the gap between the default value and actual data is roughly €18,278 in 2026, €36,556 in 2027 and €54,834 in 2028. This is an example; your product's figure is calculated from your own data. The certificate price follows the EU ETS and changes.",
      "Who carries the difference?",
      "The importer pays, but the cost usually comes back to the exporter in price negotiations, or the buyer switches supplier.",
      "How Nechh Eco-Report handles it",
      "In Eco-Report, entering the origin country, CN code, year and tonnage shows the official default value and the value including the mark-up side by side. Calculations with actual data follow the EU method, and every figure shows its source.",
    ],
  }),
  en({
    slug: "blog-cbam-50-tonne-exemption-whose-tonnage-counts",
    product: "eco-report",
    category: "CBAM",
    title: "The CBAM 50-Tonne Exemption: Whose Tonnage Counts?",
    excerpt: "\"We sell less than 50 tonnes a year, so it doesn't apply to us\" is often wrong. The threshold looks at the EU importer's total, not your sales.",
    body: [
      "Regulation (EU) 2025/2083 added a mass threshold to CBAM: if an EU importer's annual total net mass of covered goods is 50 tonnes or less, no CBAM obligation arises.",
      "Whose tonnage is counted?",
      "The threshold looks at the importer's total purchases from all suppliers in a year, not at a single exporter's sales. A buyer ordering 20 tonnes from you but 200 tonnes elsewhere is well above it.",
      "Exceptions",
      "Electricity and hydrogen are not covered by this exemption. Nor does it apply automatically; the importer states it in the customs declaration.",
      "What to do",
      "Ask your buyer about their total CBAM tonnage and whether they will need data from you. If they do, the first annual declaration for 2026 imports is due by 30 September 2027, so preparation should not be left to the last month.",
      "How Nechh Eco-Report handles it",
      "In Eco-Report the exemption check runs as soon as the tonnage is entered. If you are exempt it says so clearly; if not, you move on to the actual-data calculation.",
    ],
  }),

  // ─── HELIALOOP ───
  en({
    slug: "blog-why-whatsapp-is-not-enough-for-patient-referrals",
    product: "helialoop",
    category: "HELIALOOP",
    title: "Why WhatsApp Is Not Enough for Patient Referrals",
    excerpt: "Referring a patient to a colleague often starts with a message and gets lost there. Where referrals break down and what a structured flow changes.",
    body: [
      "When a physician refers a patient to another specialty, it usually starts with a message to a colleague they know. The message is read, the patient is called or not, and the referring physician rarely learns the outcome.",
      "Where referrals get lost",
      "The referral is buried among personal chats. Nobody knows whether the patient booked. Who referred which patient, and why, cannot be seen as a whole. Patient data is scattered across personal messaging apps.",
      "What a structured flow changes",
      "When a referral is kept as its own record, both the referring and receiving physician can see which step it is at. Clear next steps and responsibilities make it less likely that the patient falls through the gap.",
      "How HeliaLoop handles it",
      "HeliaLoop is designed to bring referral and appointment coordination between physicians and clinicians into one workspace: finding colleagues, creating and tracking referrals, messaging and availability are part of the same flow. HeliaLoop is available on Google Play.",
    ],
  }),
  en({
    slug: "blog-what-a-good-referral-note-should-contain",
    product: "helialoop",
    category: "HELIALOOP",
    title: "What Should a Good Referral Note Contain?",
    excerpt: "An incomplete referral note sends the patient through the same tests twice. The information a colleague needs at first glance.",
    body: [
      "The receiving physician's first minute is often spent asking \"why was this patient sent to me?\". A short but complete referral note saves time and spares the patient repeated tests.",
      "Core items",
      "The reason for referral and the question to be answered; relevant history and current diagnoses; medications and allergies; results and dates of tests already done; urgency; the referring physician's contact details.",
      "Closing the loop",
      "A referral does not end when the patient arrives. Sending the receiving physician's assessment back to the referrer keeps care continuous and builds trust between colleagues.",
      "Proportion in data sharing",
      "Health data is a special category of personal data. Share only what the referral needs, and do not leave it scattered in personal messaging apps.",
      "How HeliaLoop handles it",
      "In HeliaLoop a referral is created and tracked as its own record, and both physicians can see which step it is at. This article is general information, not clinical or legal advice.",
    ],
  }),
  en({
    slug: "blog-protecting-patient-data-in-physician-collaboration",
    product: "helialoop",
    category: "HELIALOOP",
    title: "Protecting Patient Data in Physician Collaboration",
    excerpt: "Health data is a special category of personal data. Principles to keep in mind when sharing it with a colleague.",
    body: [
      "Data protection laws such as Türkiye's KVKK (Law No. 6698) and the EU GDPR treat health data as a special category and attach strict conditions to processing it. A referral between colleagues is also a data transfer.",
      "Three core principles",
      "Necessity: share only what the referral requires. Legal basis: the transfer must rest on the patient's consent or a statutory exception. Security: data should not be scattered in personal photo galleries and general messaging groups.",
      "The risk of personal messaging",
      "A lab result photo sent in a general-purpose messaging app ends up in phone backups, the gallery and sometimes other chats. Who accessed which data cannot be traced afterwards.",
      "How HeliaLoop handles it",
      "HeliaLoop keeps referrals and messaging in a workspace dedicated to physicians, with a separate screen for patient consent. The physician always decides what is shared and on what legal basis. This article is not legal advice; review it with your organisation's data controller.",
    ],
  }),

  // ─── JURILOOP ───
  en({
    slug: "blog-case-referrals-between-lawyers",
    product: "juriloop",
    category: "JURILOOP",
    title: "Case Referrals Between Lawyers: Putting Collaboration on Record",
    excerpt: "Referring a matter outside your practice area to a colleague is common but usually unrecorded. Why a traceable referral helps.",
    body: [
      "Lawyers often refer a matter outside their practice area to a colleague they trust. The referral is usually made by phone or message and never recorded.",
      "Problems with unrecorded referrals",
      "It stays unclear who the client was referred to, whether the matter was accepted and where it stands. The client may also be unsure which lawyer they are working with.",
      "Mind the professional rules",
      "The legal profession has rules against soliciting work and using intermediaries. On questions such as fee sharing for referrals, always check the applicable legislation, your bar's rules of conduct and its guidance.",
      "How JuriLoop handles it",
      "JuriLoop is designed to make case referrals and working coordination between legal professionals traceable: referrals, client acceptance, the calendar and messaging sit in one workspace. JuriLoop is available on Google Play. This article is not legal advice.",
    ],
  }),
  en({
    slug: "blog-digital-collaboration-and-confidentiality-in-law-firms",
    product: "juriloop",
    category: "JURILOOP",
    title: "Digital Collaboration and Confidentiality in Law Firms",
    excerpt: "A lawyer's duty of confidentiality also covers the channel through which case information is shared. What to watch when working with colleagues.",
    body: [
      "Lawyers are bound not to disclose information entrusted to them or learned in the course of their work. That duty also concerns where and how case information is shared.",
      "Common risks",
      "Draft pleadings circulating in personal messaging groups, client documents left in phone galleries, and no way of tracing who accessed a file.",
      "Practical principles",
      "Share case information only with the colleague working on the matter; make sure the client knows about the collaboration; put documents in a channel tied to the case rather than general chats; close access when the collaboration ends.",
      "How JuriLoop handles it",
      "JuriLoop offers a workspace that keeps collaboration between colleagues in the context of the case; messages and documents are linked to the relevant workflow. This article is general information, not legal advice.",
    ],
  }),
  en({
    slug: "blog-managing-court-dates-and-duty-assignments-in-one-place",
    product: "juriloop",
    category: "JURILOOP",
    title: "Keeping Court Dates and Duty Assignments in One Place",
    excerpt: "When hearings, deadlines and legal-aid duties live in different places, clashes are inevitable. The benefit of a single calendar.",
    body: [
      "A lawyer's calendar is not just hearings: statutory deadlines, client meetings and legal-aid (CMK) duties assigned through the bar land on the same days.",
      "Where clashes come from",
      "When hearings are in the court system, meetings in the phone calendar and duty assignments in messages, none of them shows the real picture. In a busy week a missed deadline can have serious consequences.",
      "The single-source principle",
      "There should be one calendar where every appointment and deadline is entered; official records remain in the court system, but day-to-day planning is done from this single calendar. Work handed over to a colleague should be tracked from the same place.",
      "How JuriLoop handles it",
      "In JuriLoop the calendar, legal-aid duty and case referral screens sit in the same workspace, and the status of work handed to a colleague can be tracked. JuriLoop does not replace UYAP, Türkiye's court information system; official filings go through UYAP.",
    ],
  }),
];
