/** Evidence Grid: service cards use clear scope, explicit boundaries and a single conversation route rather than sales pressure. */
import { ArrowUpRight, FileCheck2, Layers3, NotebookTabs } from "lucide-react";
import { Link } from "wouter";
import { PageFrame } from "@/components/SiteShell";
import { services } from "@/lib/site";

const icons = [FileCheck2, Layers3, NotebookTabs];

export default function Services() {
  return <PageFrame title="Hizmetler" description="Nechh Robotics'in CBAM, uyum süreci ve kaynak hizmetleri."><section className="services-hero"><div className="page-hero-rail"><span>SERVICES / 01</span><i /></div><div><p className="eyebrow">HİZMETLER</p><h1>Hazırlığı tek başınıza<br /><em>taşımak zorunda değilsiniz.</em></h1></div><p>Nechh, düzenleme ve operasyon baskısının yoğunlaştığı noktalarda; hazırlık, yapılandırma ve çalışma disiplini için net bir başlangıç sunar.</p></section><section className="service-grid">{services.map((service, index) => { const Icon = icons[index]; return <article className="service-card" key={service.index}><div className="service-card-meta"><span>{service.index}</span><Icon size={23} /></div><p className="eyebrow">{service.eyebrow}</p><h2>{service.title}</h2><p>{service.summary}</p><div className="service-boundary"><span>SINIR</span><small>{service.note}</small></div><Link href={service.href} className="route-link">Ön görüşme isteyin <ArrowUpRight size={18} /></Link></article>; })}</section><section className="service-process"><div><p className="eyebrow">ÇALIŞMA BİÇİMİ</p><h2>Belirsizliği azaltan<br /><em>üç net adım.</em></h2></div><div className="service-steps"><article><span>01</span><h3>Bağlamı dinleriz</h3><p>Kapsamı, mevcut çalışmayı ve en zor düğümü birlikte tanımlarız.</p></article><article><span>02</span><h3>Çerçeveyi kurarız</h3><p>Veri, belge, kontrol ve sorumluluk akışını uygun çalışma alanına yerleştiririz.</p></article><article><span>03</span><h3>Sonraki adımı açıklarız</h3><p>Ürünün, kaynağın veya hizmetin nerede değer üreteceğini sınırlarıyla birlikte belirtiriz.</p></article></div></section></PageFrame>;
}

export function EnglishServices() {
  return <PageFrame locale="en" title="Services" description="Nechh Robotics services for CBAM preparation, compliance processes and resources."><section className="services-hero"><div className="page-hero-rail"><span>SERVICES / 01</span><i /></div><div><p className="eyebrow">SERVICES</p><h1>You do not have to carry<br /><em>the preparation alone.</em></h1></div><p>Nechh offers a clear starting point for preparation, process structure and working discipline where regulatory and operational pressure converges.</p></section><section className="service-grid">{services.map((service, index) => { const Icon = icons[index]; const content = [
    { eyebrow: "CBAM / AUTHORISED DECLARANT", title: "CBAM application preparation", summary: "Scoping, document preparation and process coordination for the Authorised Declarant journey.", note: "This service does not replace legal advice, accredited verification or an official declaration." },
    { eyebrow: "COMPLIANCE / PROCESS DESIGN", title: "Compliance working context", summary: "A working starting point to clarify data, documents and controls across compliance processes.", note: "Scope is clarified in writing after an initial needs conversation." },
    { eyebrow: "RESOURCES / DIGITAL PACKS", title: "Start with your own team", summary: "A resource approach with guides, checklists and editable working templates for internal preparation.", note: "Online payment is not active; delivery and licensing are clarified by email." },
  ][index]; return <article className="service-card" key={service.index}><div className="service-card-meta"><span>{service.index}</span><Icon size={23} /></div><p className="eyebrow">{content.eyebrow}</p><h2>{content.title}</h2><p>{content.summary}</p><div className="service-boundary"><span>BOUNDARY</span><small>{content.note}</small></div><Link href="/en/contact" className="route-link">Request a conversation <ArrowUpRight size={18} /></Link></article>; })}</section><section className="service-process"><div><p className="eyebrow">HOW WE WORK</p><h2>Three clear steps<br /><em>to reduce uncertainty.</em></h2></div><div className="service-steps"><article><span>01</span><h3>Listen to the context</h3><p>We define the scope, current work and the most difficult point in the process.</p></article><article><span>02</span><h3>Build a frame</h3><p>We place data, documents, controls and responsibilities into an appropriate working context.</p></article><article><span>03</span><h3>Clarify the next step</h3><p>We state where a product, resource or service can create value, including its boundaries.</p></article></div></section></PageFrame>;
}
